tailscale_hostname: jenkins-server
tailscale_secret_id: tailscale/jenkins-auth-key
tailscale_tags: ["jenkins"]
ansible_ssh_private_key_file: /home/tsukinobi/.ssh/stealth.pem
github_pat_secret_id: qrgenix/github-pat
github_webhook_secret_id: qrgenix/github-webhook
ghcr_secret_id: qrgenix/ghcr-token
slack_secret_id: qrgenix/slack-webhook
jenkins_admin_password_secret_id: qrgenix/jenkins-admin-password
jenkins_admin_user: admin
