services:
  backend:
    build:
      context: ./backend-django            # same Dockerfile you run in prod
      dockerfile: Dockerfile               # (gunicorn or uwsgi etc.)
    image: qrgenix-backend:prod            # local name; we retag in Jenkins

  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile               # ← the multi-stage Node→NGINX file
    image: qrgenix-frontend:prod
