# Traefik ansible role

- name: Copy Helm values files to app node (as normal user)
  copy:
    src: traefik-values.yaml
    dest: /tmp/traefik-values.yaml
    mode: "0644"

- name: Deploy or Upgrade Traefik via Helm
  kubernetes.core.helm:
    name: traefik
    update_repo_cache: true
    chart_repo_url: https://traefik.github.io/charts
    chart_ref: traefik
    release_namespace: traefik
    create_namespace: true
    values_files:
      - /tmp/traefik-values.yaml
    state: present
    wait: true
