# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrgenix-backend
  namespace: qrgenix
  labels:
    app.kubernetes.io/managed-by: qrgenix
    app: qrgenix-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrgenix-backend
  template:
    metadata:
      labels:
        app: qrgenix-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/sheriefs/qrgenix-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: qrgenix.settings
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
