# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: qrgenix-backend
  namespace: qrgenix
  labels:
    app.kubernetes.io/managed-by: qrgenix
spec:
  selector:
    app: qrgenix-backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
