# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: qrgenix-frontend
  namespace: qrgenix
  labels:
    app.kubernetes.io/managed-by: qrgenix
spec:
  selector:
    app: qrgenix-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
