apiVersion: v1
kind: ConfigMap
metadata:
  name: qrgenix-nginx-config
  namespace: qrgenix

data:
  nginx.conf: |
    events {}

    http {
        upstream frontend {
            server qrgenix-frontend.qrgenix.svc.cluster.local:5173;
        }

        upstream backend {
            server qrgenix-backend.qrgenix.svc.cluster.local:8000;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /api/ {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
