# PostgreSQL PersistentVolumeClaim
# touch: trigger k8s apply
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: qrgenix
  labels:
    app.kubernetes.io/managed-by: qrgenix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
