---
- name: Download K3s installer script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: "0755"
  become: true

- name: Install K3s
  shell: /tmp/install-k3s.sh
  args:
    creates: /usr/local/bin/k3s
  become: true

- name: Enable and start K3s
  systemd:
    name: k3s
    state: started
    enabled: true
  become: true

- name: Ensure .kube directory exists
  file:
    path: /root/.kube
    state: directory
    mode: "0700"
  become: true

- name: Copy K3s kubeconfig to default location
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Ensure kubectl is available via symlink
  file:
    src: /usr/local/bin/kubectl
    dest: /usr/bin/kubectl
    state: link
    force: true
  become: true

- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
    update_cache: true
  become: true

- name: Install Kubernetes Python bindings (via apt)
  apt:
    name: python3-kubernetes
    state: present
  become: true
