# /roles/k3s/tasks/main.yaml

- name: Download K3s installer script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: "0755"

- name: Install K3s with traefik disabled
  command:
  args:
    cmd: /tmp/install-k3s.sh
    creates: /usr/local/bin/k3s
  environment:
    INSTALL_K3S_EXEC: "server --disable=traefik"

- name: Enable and start K3s
  systemd:
    name: k3s
    state: started
    enabled: true

- name: Ensure .kube directory exists
  file:
    path: /root/.kube
    state: directory
    mode: "0700"

- name: Copy K3s kubeconfig to default location
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: "0600"

- name: Ensure kubectl is available via symlink
  file:
    src: /usr/local/bin/kubectl
    dest: /usr/bin/kubectl
    state: link
    force: true
