- name: Download K3s installer script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: "0755"

- name: Install K3s
  shell: /tmp/install-k3s.sh
  args:
    creates: /usr/local/bin/k3s

- name: Enable and start k3s
  systemd:
    name: k3s
    state: started
    enabled: true
