# roles/backend/tasks/main.yaml
- name: Pull latest backend container image
  shell: docker pull ghcr.io/<your-user>/qrgenix-backend:latest
  args:
    warn: false

- name: Restart backend deployment in Kubernetes
  shell: kubectl rollout restart deployment qrgenix-backend -n qrgenix
  args:
    warn: false
