# roles/backend/tasks/main.yaml
- name: Pull latest backend container image

  shell: docker pull ghcr.io/{{ ghcr_user }}/qrgenix-backend:latest

- name: Restart backend deployment in Kubernetes
  shell: kubectl rollout restart deployment qrgenix-backend -n qrgenix
