# roles/nginx/tasks/main.yaml

- name: Create directory for nginx config
  file:
    path: /opt/nginx
    state: directory
    mode: "0755"

- name: Copy nginx config to target
  copy:
    src: nginx.conf
    dest: /opt/nginx/nginx.conf
    mode: "0644"

- name: Run nginx container with mounted config
  docker_container:
    name: nginx
    image: nginx:alpine
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
