# roles/tailscale/tasks/main.yaml
- name: Fetch Tailscale authkey from AWS Secrets Manager
  set_fact:
    ts_authkey: "{{ lookup('amazon.aws.secretsmanager_secret', tailscale_secret_id, region=aws_region) }}"

- name: Install and configure Tailscale
  include_role:
    name: artis3n.tailscale.machine
  vars:
    state: present
    tailscale_authkey: "{{ ts_authkey }}"
    tailscale_args: "--accept-routes --hostname={{ tailscale_hostname }} --operator={{ ansible_user }}"

- name: Create Tailscale cert directory
  file:
    path: /etc/ssl/tailscale
    state: directory
    mode: "0755"

- name: Generate Tailscale certificates
  command: >
    tailscale cert
    --cert-file {{ tailscale_cert_path }}/{{ tailscale_hostname }}.{{ tailscale_domain }}.crt
    --key-file {{ tailscale_cert_path }}/{{ tailscale_hostname }}.{{ tailscale_domain }}.key
    {{ tailscale_hostname }}.{{ tailscale_domain }}

- name: Set permissions on .cert file
  file:
    path: "{{ tailscale_cert_path }}/{{ tailscale_hostname }}.{{ tailscale_domain }}.crt"
    mode: "0444"

- name: Set permissions on .key file
  file:
    path: "{{ tailscale_cert_path }}/{{ tailscale_hostname }}.{{ tailscale_domain }}.key"
    mode: "0400"
